apiVersion: v1
kind: Pod
metadata:
  name: demo-cpu
spec:
  containers:
    - name: democpu
      image: vish/stress
      resources:
        requests:
          cpu: "2000"
        limits:
          cpu: "2000"
      args:
        - -cpus
        - "0.01"
