apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend
          image: localhost:5000/frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT_FRONTEND
              value: "3000"
            - name: SERVICE_BACKEND1
              value: http://backend1-svc/api
