apiVersion: v1
kind: Secret
metadata:
  name: sc-parameters
type: Opaque
data:
  user: c2VyZ2lvLmhpZGFsZ28=
  pass: M2xNdW4wRXNAbmNob3lhajNOPU8=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app
spec:
  replicas: 5
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - name: web01
          image: nginx:alpine
          env:
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: sc-parameters
                  key: user
            - name: PASS
              valueFrom:
                secretKeyRef:
                  name: sc-parameters
                  key: pass
