apiVersion: v1
kind: Namespace
metadata:
  name: nsp-dev
  labels:
    env: dev
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-dev
  namespace: nsp-dev
spec:
  limits:
    - defaultRequest:
        memory: 256Mi
        cpu: 0.5
      default:
        memory: 512Mi
        cpu: 1
      type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-default
  namespace: nsp-dev
  labels:
    env: dev
spec:
  containers:
    - name: container-name
      image: nginx:alpine
