apiVersion: v1
kind: Namespace
metadata:
  name: nsp-dev
  labels:
    env: dev
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-dev
  namespace: nsp-dev
spec:
  limits:
    - max:
        memory: 1Gi
        cpu: 1
      min:
        memory: 100Mi
        cpu: 100m
      type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-default
  namespace: nsp-dev
  labels:
    env: dev
spec:
  containers:
    - name: container-name
      image: nginx:alpine
      resources:
        limits:
          memory: 150Mi
          cpu: 1
