apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-pod-container
      image: nginx:alpine
      volumeMounts:
        - name: nginx-vol
          mountPath: /var/log/nginx
  volumes:
    - name: nginx-vol
      emptyDir: {}
