apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: contenedor1
          image: nginx:alpine
