apiVersion: v1
kind: Namespace
metadata:
  name: nsp-dev
  labels:
    env: dev
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: demo-quota
  namespace: nsp-dev
spec:
  hard:
    pods: "3"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app
  namespace: nsp-dev
spec:
  replicas: 7
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - name: web01
          image: nginx:alpine
