apiVersion: v1
kind: Namespace
metadata:
  name: nsp-dev
  labels:
    env: dev
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: demo-quota
  namespace: nsp-dev
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app
  namespace: nsp-dev
spec:
  replicas: 5
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - name: web01
          image: nginx:alpine
          resources:
            requests:
              memory: 500Mi
              cpu: 500m
            limits:
              memory: 500Mi
              cpu: 500m
