apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-parameters
data:
  db_host: dev.host.local
  db_user: dev.user
  db_pass: dev.pass
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app
spec:
  replicas: 5
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - name: web01
          image: nginx:alpine
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: cm-parameters
                  key: db_host
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: cm-parameters
                  key: db_user
            - name: DB_PASS
              valueFrom:
                configMapKeyRef:
                  name: cm-parameters
                  key: db_pass
