version: "3.8"

services:
  frontend:
    image: 282865065290.dkr.ecr.us-east-1.amazonaws.com/frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - BASE_DIR=frontend
    container_name: frontend-ms
    ports:
      - 5400:${PORT_FRONTEND}
    env_file:
      - .env
    environment:
      - SERVICE_BACKEND1=http://localhost:5500/api/message
    networks:
      - net-01

  backend1:
    image: 282865065290.dkr.ecr.us-east-1.amazonaws.com/backend1
    build:
      context: .
      dockerfile: backend1/Dockerfile
      args:
        - BASE_DIR=backend1
    container_name: backend1-ms
    ports:
      - 5500:${PORT_BACKEND1}
    env_file:
      - .env
    environment:
      - SERVICE_BACKEND2=http://backend2-ms:3200/api/message
    networks:
      - net-01
      - net-02

  backend2:
    image: 282865065290.dkr.ecr.us-east-1.amazonaws.com/backend2
    build:
      context: .
      dockerfile: backend2/Dockerfile
      args:
        - BASE_DIR=backend2
    container_name: backend2-ms
    env_file:
      - .env
    networks:
      - net-02

networks:
  net-01:
    driver: bridge
    name: net-01
  net-02:
    driver: bridge
    name: net-02
