version: "3.8"

services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - BASE_DIR=frontend
    container_name: frontend-ms
    ports:
      - 5400:${PORT_FRONTEND}
    env_file:
      - .env
    environment:
      - SERVICE_BACKEND1=http://localhost:5500/api/message
    networks:
      - net-01
    volumes:
      - ./vol-frontend:/app/public
      - ./vol-code-frontend:/app/src
    command: npm run start:dev

  backend1:
    image: backend1
    build:
      context: .
      dockerfile: backend1/Dockerfile
      args:
        - BASE_DIR=backend1
    container_name: backend1-ms
    ports:
      - 5500:${PORT_BACKEND1}
    env_file:
      - .env
    environment:
      - SERVICE_BACKEND2=http://backend2-ms:3200/api/message
    networks:
      - net-01
      - net-02

  backend2:
    image: backend2
    build:
      context: .
      dockerfile: backend2/Dockerfile
      args:
        - BASE_DIR=backend2
    container_name: backend2-ms
    env_file:
      - .env
    networks:
      - net-02

networks:
  net-01:
    driver: bridge
    name: net-01
  net-02:
    driver: bridge
    name: net-02
